### ISSUE TITLE
Error in parset - TB instead of GB 

### ISSUE THREAD

**Issue by pdacity** [pgconfig/api#20]
In the generated config there are terabytes instead of gigabytes (see screenshot)

Total memory size is 8 gigabytes, shared_buffers should be 2 gigabytes

![изображение](https://github.com/pgconfig/api/assets/30793797/f0eedd4a-58e4-42c9-a326-4636046fb08a)

**Comment by sebastianwebber** [comment]
if you have 8gb of RAM, just set 8: 

<img width="1184" alt="image" src="https://github.com/pgconfig/api/assets/2515929/67bcd1e4-3577-485e-9269-ff814b857364">

Since the values are expected in GB, you requested 8TB.
